# Regression

## Correlation

### Main Analysis

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_1_Main-Analysis.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Main Analysis Partial

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_2_Main-Analysis-Partial.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Assumption Checks

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_3_Assumption-Checks.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Plots

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_4_Plots.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Pairwise

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_5_Pairwise.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Various Coefficients

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/1_Correlation/Correlation_6_Various-Coefficients.mp4" type="video/mp4">Your browser does not support the video tag.</video>

## Regression

### Main Analysis Single Predictor

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_1_Main-Analysis-Single-Predictor.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Main Analysis Multiple Predictors

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_2_Main-Analysis-Multiple-Predictors.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Hierarchical Regression

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_3_Hierarchical-Regression.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Assumption Checks

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_4_Assumption-Checks.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Bootstrap Confidence Interval

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_5_Bootstrap-Confidence-Interval.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Cooks Distance

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_6_Cooks-Distance.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Logistic Regression

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/2_Regression/Regression_7_Logistic-Regression.mp4" type="video/mp4">Your browser does not support the video tag.</video>

## Bayesian Correlation

### Main Analysis

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/3_Bayesian_Correlation/Bayesian_Correlation_1_Main-Analysis.mp4" type="video/mp4">Your browser does not support the video tag.</video>

## Bayesian Regression

### Main Analysis

<video width="600" controls><source src="/jasp-video-library/assets/videos/All_Regression/4_Bayesian_Regression/Byesian_Regression_1_Main-Analysis.mp4" type="video/mp4">Your browser does not support the video tag.</video>

