# Getting-Started

## Getting-Started

### Loading Data

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_01_Loading-Data.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Renaming Categories

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_02_Renaming-Categories.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Reordering Categories

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_03_Reordering-Categories.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Center Variable

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_04_Center-Variable.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Compute New Column

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_05_Compute-New-Column.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Use If Else

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_05_Use-If-Else.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Filter by Group

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_06_Filter-by-Group.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Filter Drag and Drop

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_07_Filter-Drag-and-Drop.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Convert to Ranks

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_08_Convert-to-Ranks.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Enable R Module

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_09_Enable-R-Module.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Drag and Drop RowMean

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_10_Drag-and-Drop-RowMean.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Drag and Drop RowSum

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_11_Drag-and-Drop-RowSum.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### R RowSum

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_12_R-RowSum.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### R RowMean

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_13_R-RowMean.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Add Levels

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_14_Add-Levels.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Reverse Code Single

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_15_Reverse-Code-Single.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Reverse Code Multiple

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_16_Reverse-Code-Multiple.mp4" type="video/mp4">Your browser does not support the video tag.</video>

### Statistical Test Flowchart

<video width="600" controls><source src="/jasp-video-library/assets/videos/Getting-Started/Getting_Started_17_Statistical-Test-Flowchart.mp4" type="video/mp4">Your browser does not support the video tag.</video>

