# All ANOVA

## ANCOVA

|Title              |Link                                                                                         |
|:------------------|:--------------------------------------------------------------------------------------------|
|Main Analysis      |<a href="/3_All_ANOVA/ANCOVA/ANCOVA_1_Main-Analysis.mp4" target="_blank">Open Video</a>      |
|Descriptives Plots |<a href="/3_All_ANOVA/ANCOVA/ANCOVA_2_Descriptives-Plots.mp4" target="_blank">Open Video</a> |

## ANOVA Factorial

|Title                           |Link                                                                                                                            |
|:-------------------------------|:-------------------------------------------------------------------------------------------------------------------------------|
|Effect Size                     |<a href="/3_All_ANOVA/ANOVA_Factorial/ANOVA_Factorial_3_Effect-Size.mp4" target="_blank">Open Video</a>                         |
|Simple Main Effects             |<a href="/3_All_ANOVA/ANOVA_Factorial/ANOVA_Factorial_7_Simple-Main-Effects.mp4" target="_blank">Open Video</a>                 |
|Nonparametric                   |<a href="/3_All_ANOVA/ANOVA_Factorial/ANOVA_Factorial_8_Nonparametric.mp4" target="_blank">Open Video</a>                       |
|Main Analysis                   |<a href="/3_All_ANOVA/ANOVA_Factorial/TBD_ANOVA_Factorial_1_Main-Analysis.mp4" target="_blank">Open Video</a>                   |
|Normality And Homogeniety Check |<a href="/3_All_ANOVA/ANOVA_Factorial/TBD_ANOVA_Factorial_2_Normality-And-Homogeniety-Check.mp4" target="_blank">Open Video</a> |
|Plots                           |<a href="/3_All_ANOVA/ANOVA_Factorial/TBD_ANOVA_Factorial_4_Plots.mp4" target="_blank">Open Video</a>                           |
|Contrasts                       |<a href="/3_All_ANOVA/ANOVA_Factorial/TBD_ANOVA_Factorial_5_Contrasts.mp4" target="_blank">Open Video</a>                       |
|Post Hoc Tests                  |<a href="/3_All_ANOVA/ANOVA_Factorial/TBD_ANOVA_Factorial_6_Post-Hoc-Tests.mp4" target="_blank">Open Video</a>                  |

## ANOVA Oneway

|Title                           |Link                                                                                                                  |
|:-------------------------------|:---------------------------------------------------------------------------------------------------------------------|
|Normality And Homogeniety Check |<a href="/3_All_ANOVA/ANOVA_Oneway/ANOVA_Oneway_2_Normality-And-Homogeniety-Check.mp4" target="_blank">Open Video</a> |
|Effect Size                     |<a href="/3_All_ANOVA/ANOVA_Oneway/ANOVA_Oneway_3_Effect-Size.mp4" target="_blank">Open Video</a>                     |
|Main Analysis                   |<a href="/3_All_ANOVA/ANOVA_Oneway/TBD_ANOVA_Oneway_1_Main-Analysis.mp4" target="_blank">Open Video</a>               |

## ANOVA Repeated

|Title            |Link                                                                                                 |
|:----------------|:----------------------------------------------------------------------------------------------------|
|Main Analysis    |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_1_Main-Analysis.mp4" target="_blank">Open Video</a>    |
|Homogeneity Test |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_2_Homogeneity-Test.mp4" target="_blank">Open Video</a> |
|Plots            |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_3_Plots.mp4" target="_blank">Open Video</a>            |
|Effect Size      |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_4_Effect-Size.mp4" target="_blank">Open Video</a>      |
|Contrasts        |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_5_Contrasts.mp4" target="_blank">Open Video</a>        |
|Post Hoc Tests   |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_6_Post-Hoc-Tests.mp4" target="_blank">Open Video</a>   |
|Sphericity Test  |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_7_Sphericity-Test.mp4" target="_blank">Open Video</a>  |
|QQ Plot          |<a href="/3_All_ANOVA/ANOVA_Repeated/ANOVA_RM_8_QQ-Plot.mp4" target="_blank">Open Video</a>          |

## Bayesian ANCOVA

|Title         |Link                                                                                                      |
|:-------------|:---------------------------------------------------------------------------------------------------------|
|Main Analysis |<a href="/3_All_ANOVA/Bayesian_ANCOVA/Bayesian_ANCOVA_1_Main-Analysis.mp4" target="_blank">Open Video</a> |

## Bayesian ANOVA Factorial

|Title         |Link                                                                                                              |
|:-------------|:-----------------------------------------------------------------------------------------------------------------|
|Main Analysis |<a href="/3_All_ANOVA/Bayesian_ANOVA_Factorial/Bayesian_ANOVA_1_Main-Analysis.mp4" target="_blank">Open Video</a> |

## Bayesian ANOVA Oneway

|Title         |Link                                                                                                                  |
|:-------------|:---------------------------------------------------------------------------------------------------------------------|
|Main Analysis |<a href="/3_All_ANOVA/Bayesian_ANOVA_Oneway/Bayesian_ANOVA_Oneway_1_Main-Analysis.mp4" target="_blank">Open Video</a> |

## Bayesian ANOVA Repeated

|Title         |Link                                                                                                                      |
|:-------------|:-------------------------------------------------------------------------------------------------------------------------|
|Main Analysis |<a href="/3_All_ANOVA/Bayesian_ANOVA_Repeated/Bayesian_ANOVA_Repeated_1_Main-Analysis.mp4" target="_blank">Open Video</a> |

